### PR TITLE
Add github pull requests references

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
So that we can checkout them as well

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
With this, we can use the cucumber from the same PR we build the packages (in the context of running acceptance tests on PR)

**Review by juliogonzalez — COMMENTED** [review]
LGTM, but please run the unit test, in case they need to be updated.

**Review by srbarrios — APPROVED** [review]
Awesome thank you!

**Comment by jordimassaguerpla** [comment]
I run unittests and there is one failure, the same if I run it on master branch.

**Comment by juliogonzalez** [comment]
@jordimassaguerpla what's the failure? Last time I ran the tests, I had none.

**Comment by jordimassaguerpla** [comment]
```
python3 -m unittest
......VAR=555
..Removing tags and fetching from <MagicMock name='Repository().remotes.__getitem__().url' id='140637350808264'>...
mytag seems to be a tag
Checking out
Removing tags and fetching from <MagicMock name='Repository().remotes.__getitem__().url' id='140637350808264'>...
Checking out
Performing hard reset to ignore local changes
.Removing tags and fetching from <MagicMock name='Repository().remotes.__getitem__().url' id='140637351066816'>...
Checking out
Performing hard reset to ignore local changes
....mytag seems to be a tag
mytag seems to be a tag
Checking out
Checking out
Performing hard reset to ignore local changes
.Removing tags and fetching from <MagicMock name='Repository().remotes.__getitem__().url' id='140637351560864'>...
mytag seems to be a tag
Checking out
...F........
======================================================================
FAIL: test_sort_test_files_by_mtime (test.test_junit.TestJunit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jordi/work/galaxy/terracumber/terracumber/test/test_junit.py", line 18, in test_sort_test_files_by_mtime
    self.assertListEqual(self.junit.sort_test_files_by_mtime(), file_list)
AssertionError: Lists differ: ['tes[46 chars]dary-srv_delete_channel_from_ui.xml', 'test/re[485 chars]xml'] != ['tes[46 chars]dary-trad_centos_client.xml', 'test/resources/[485 chars]xml']

First differing element 0:
'test[18 chars]ailures/TEST-features-secondary-srv_delete_channel_from_ui.xml'
'test[18 chars]ailures/TEST-features-secondary-trad_centos_client.xml'

+ ['test/resources/junit/failures/TEST-features-secondary-trad_centos_client.xml',
+  'test/resources/junit/failures/TEST-features-secondary-srv_virtual_host_manager.xml',
- ['test/resources/junit/failures/TEST-features-secondary-srv_delete_channel_from_ui.xml',
? ^                                                           ^ -------------- ^^^^^

+  'test/resources/junit/failures/TEST-features-secondary-srv_users.xml',
? ^                                                           ^^  ^

+  'test/resources/junit/failures/TEST-features-secondary-srv_test_maintenance_windows.xml',
+  'test/resources/junit/failures/TEST-features-secondary-srv_power_management.xml',
   'test/resources/junit/failures/TEST-features-secondary-srv_delete_channel_with_tool.xml',
-  'test/resources/junit/failures/TEST-features-secondary-srv_power_management.xml',
?                                                             ^^^ ^ ^  ^^  ^^^     ^

+  'test/resources/junit/failures/TEST-features-secondary-srv_delete_channel_from_ui.xml']
?                                                             ^ ^^^^ ^^  ^ +++++ ^^^     ^

-  'test/resources/junit/failures/TEST-features-secondary-srv_test_maintenance_windows.xml',
-  'test/resources/junit/failures/TEST-features-secondary-srv_users.xml',
-  'test/resources/junit/failures/TEST-features-secondary-srv_virtual_host_manager.xml',
-  'test/resources/junit/failures/TEST-features-secondary-trad_centos_client.xml']

----------------------------------------------------------------------
Ran 26 tests in 0.371s

FAILED (failures=1)
```

**Pull request merged**
